### ISSUE TITLE
Error in units-css: Module build failed: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by bherila** [barbar/vortigern#138]
Looks like there is an error in units-css that's causing an issue at runtime (it's dumped in the browser... not in webpack). Is there a specific version of units-css that is known to be working with Vortigern?

Thanks,
Ben

```
ERROR in ./~/css-loader?modules&importLoaders=2&localIdentName=[local]___[hash:base64:5]!./~/postcss-loader!./src/app/containers/Home/style.css
Module build failed: ReferenceError: document is not defined
    at C:\Users\ucadmin\Documents\uc\admin\node_modules\units-css\lib\utilities.js:114:43
    at Object.<anonymous> (C:\Users\ucadmin\Documents\uc\admin\node_modules\units-css\lib\utilities.js:117:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ucadmin\Documents\uc\admin\node_modules\units-css\lib\conversions\length.js:6:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
 @ ./src/app/containers/Home/style.css 4:14-197 13:2-17:4 14:20-203
 @ ./src/app/containers/Home/index.tsx
 @ ./src/app/containers/index.tsx
 @ ./src/app/routes/index.tsx
 @ ./src/client.tsx
 @ multi webpack-hot-middleware/client?reload=true ./src/client.tsx ./src/vendor/main.ts
```

**Comment by bherila** [comment]
I think maybe this is due to me adding this code...

```typescript
if (typeof(window) === 'undefined') {
	(global as any).window = new Object();
}
```

... to attempt to polyfill the Window object, to avoid an issue with the Plottable library ... 

```js
// plottable\build\src\utils\arrayUtils.js:7
var nativeArray = window.Array;
```

so now I have gone back on this change and will be filing a PR with Plottable.

**Comment by bherila** [comment]
Problem solved.
