### ISSUE TITLE
Cannot build on OSX

### ISSUE THREAD

**Issue by bherila** [barbar/vortigern#149]
Due to https://github.com/yarnpkg/yarn/issues/786

Suggest replacing yarn usage with just regular npm?

**Comment by bherila** [comment]
@altayaydemir this is still an issue

Would you take a PR for a package-lock.json if I were to make one? Or are you dead-set on yarn?

**Comment by altaywtf** [comment]
@bherila lets ask @batuhan

**Comment by bherila** [comment]
Thanks. FWIW, I've pretty much stopped using yarn due to this problem.

**Comment by eduardonunesp** [comment]
Yeah, not working o OSX, using `npm` or `yarn` the problem still there

```
ERROR in ./node_modules/css-loader?modules&importLoaders=2&localIdentName=[local]___[hash:base64:5]!./node_modules/postcss-loader!./src/app/components/Header/style.css
Module build failed: Error: No configuration provided for /Sandbox/ReputationHunt/src/app/components/Header/style.css
    at module.exports (/Sandbox/ReputationHunt/node_modules/stylelint/lib/utils/configurationError.js:8:27)
    at stylelint._fullExplorer.load.then.then.config (/Sandbox/ReputationHunt/node_modules/stylelint/lib/getConfigForFile.js:39:13)
    at <anonymous>
 @ ./src/app/components/Header/style.css 4:14-197 18:2-22:4 19:20-203
 @ ./src/app/components/Header/index.tsx
 @ ./src/app/components/index.tsx
 @ ./src/app/containers/App/index.tsx
 @ ./src/app/containers/index.tsx
 @ ./src/app/routes/index.tsx
 @ ./src/client.tsx
 @ multi webpack-hot-middleware/client?reload=true ./src/client.tsx ./src/vendor/main.ts
```

**Comment by chin2km** [comment]
Any update on this yet?

**Comment by bherila** [comment]
Try upgrading yarn and npm, somehow it is working for me.
